### ISSUE TITLE
YelpPath Final Commit

### ISSUE THREAD

**Issue by mceraso** [mceraso/Yelp-Path#1]
Hi Codepath! Check out my assignment from this week! Thank you! /cc @codepathreview

Michael

**Comment by minhchau273** [comment]
Hi Michael,
Please put the `search bar` in the `navigation bar`. This is a required functionality.
Thanks.

**Comment by mceraso** [comment]
Hi Chau Vo, @minhchau273

Please see my updated App. Thank you!

**Comment by minhchau273** [comment]
:+1: Nice work! This primary challenge of this homework was to learn how to use AutoLayout to build adaptive UI's that work across many different screen sizes and orientations. If you haven't already, we recommend going back and running your homework again while rotating the device / simulator to ensure your AutoLayout constraints function as expected.

### Some small comments:
- Good job with the customizing the UI :star2: 
- Nice work specifying the Auto Layout constraints.
- It's a little weird when there's a gray gap at the top of table view.
  <img width="318" alt="screen shot 2016-02-16 at 6 39 29 pm" src="https://cloud.githubusercontent.com/assets/12395213/13075315/c05fe05c-d4dc-11e5-8a1f-97e98f808d1d.png">
- For now, you only search within the current restaurants. In this assignment, you have to call the api to search the restaurants.
- That would be nice is if you handled the "no results" case gracefully, as well as didn't show empty gray lines when there is only 1 result.

We have a detailed [Project 3 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_3_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
